### ISSUE TITLE
 TODO: Pynocchio Comic Reader

### ISSUE THREAD

**Issue by mstuttgart** [pynocchio/pynocchio#21]
List of improviments:
- [x] Database file save in .config directory
- [x] Add Coveralls and Travis support
- [x] Add "Open Folder" option.
- [x] Pynocchio using PySide and uicfiles
- [x] Add persist rotate and mirror option
- [x] Add others language support
- [x] Add mime type open file support
- [x] Double page read mode
- [x] Optimize load image
- [ ] Add Settings Dialog.
- [ ] Add language select option in settings dialog
- [ ] Add mirror image option
- [ ] Add PDF support
- [ ] Add continuos image read mode
- [ ] Add frame read mode
- [ ] Add print dialog
- [ ] Info comic dialog
- [ ] Page thumbanails
- [ ] Update install instructions in github and pynocchio siute to pyqt5
- [ ] Create deploy with PyQt5Deploy
- [ ] Add Unittest to base code. Code coverage >= 50%

This list is deprecated. It is replaced by: https://github.com/orgs/pynocchio/projects/1
